trigger: none

pool:
  vmImage: 'windows-latest'

jobs:
- deployment: InitEnv
  environment: AzdoTools-Shared
  strategy:
    runOnce:
      deploy:
        steps:
        - script: echo "Initializing environment..."
