trigger:
  branches:
    include:
      - main

parameters:
  - name: appName
    type: string
    default: 'AzdoTools'
  - name: environments
    type: object
    default:
      dev:
        location: 'centralus'
        resourceGroup: 'AzdoTools-RG-Dev'
      test:
        location: 'centralus'
        resourceGroup: 'AzdoTools-RG-Test'
      prod:
        location: 'centralus'
        resourceGroup: 'AzdoTools-RG-Prod'

stages:
- ${{ each env in parameters.environments }}:
  - stage: Deploy_${{ env.key }}
    displayName: 'Deploy ${{ parameters.appName }} to ${{ env.key }}'
    jobs:
    - template: pipelines/templates/deploy-environment.yml
      parameters:
        appName: ${{ parameters.appName }}
        environmentName: ${{ env.key }}
        location: ${{ env.value.location }}
        resourceGroup: ${{ env.value.resourceGroup }}
