# ... parameter block remains unchanged ...

stages:
# 🧭 Shared Infrastructure Attempts
- stage: TryHostedShared
  condition: eq(parameters.useHostedAgent, true)
  jobs:
  - job: DeploySharedHosted
    pool:
      name: ${{ parameters.hostedAgentName }}
      vmImage: 'ubuntu-latest'
    steps:
    - script: echo "Using agent: $(Agent.Name)"
      displayName: 'Agent Info'
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'HolyCheese-ServiceConnection'
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          echo "Deploying shared infra via HostedAgent..."
          az deployment sub create \
            --location centralus \
            --template-file infra/shared-infrastructure.bicep \
            --parameters \
              subscriptionId=${{ parameters.subscriptionId }}

- stage: FallbackSharedLocal
  condition: and(eq(parameters.useHostedAgent, true), failed())
  jobs:
  - job: DeploySharedLocalFallback
    pool:
      name: ${{ parameters.localAgentName }}
    steps:
    - script: |
        echo "Fallback triggered"
        echo "##vso[task.setvariable variable=sharedAgentFallback;isOutput=true]true"
      displayName: 'Mark Fallback Active'
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'HolyCheese-ServiceConnection'
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          az deployment sub create \
            --location centralus \
            --template-file infra/shared-infrastructure.bicep \
            --parameters \
              subscriptionId=${{ parameters.subscriptionId }}

- stage: ProvisionShared
  condition: eq(parameters.useHostedAgent, false)
  jobs:
  - job: DeploySharedInfra
    pool:
      name: ${{ parameters.localAgentName }}
    steps:
    - script: echo "Using agent: $(Agent.Name)"
      displayName: 'Agent Info'
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'HolyCheese-ServiceConnection'
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          az deployment sub create \
            --location centralus \
            --template-file infra/shared-infrastructure.bicep \
            --parameters \
              subscriptionId=${{ parameters.subscriptionId }}

# 🚀 Environment Deployments (Looped)
- ${{ each env in parameters.environments }}:
  - stage: TryHosted_${{ env.key }}
    displayName: 'Deploy ${{ env.key }} via Hosted Agent'
    condition: eq(parameters.useHostedAgent, true)
    jobs:
    - job: DeployHosted_${{ env.key }}
      pool:
        name: ${{ parameters.hostedAgentName }}
        vmImage: 'ubuntu-latest'
      steps:
      - script: echo "Using agent: $(Agent.Name)"
        displayName: 'Agent Info'
      - task: AzureCLI@2
        inputs:
          azureSubscription: 'HolyCheese-ServiceConnection'
          scriptType: bash
          scriptLocation: inlineScript
          inlineScript: |
            az deployment sub create \
              --location ${{ env.value.location }} \
              --template-file infra/deploy-environment.bicep \
              --parameters \
                appName=AzdoTools \
                environmentName=${{ env.key }} \
                location=${{ env.value.location }} \
                subscriptionId=${{ parameters.subscriptionId }}
      - script: echo "##vso[task.setvariable variable=${{ env.key }}AgentFallback;isOutput=true]false"
        displayName: 'Mark Hosted Deploy Success'

  - stage: Fallback_${{ env.key }}
    displayName: 'Fallback to Local Agent for ${{ env.key }}'
    condition: and(eq(parameters.useHostedAgent, true), failed())
    jobs:
    - job: DeployFallback_${{ env.key }}
      pool:
        name: ${{ parameters.localAgentName }}
      steps:
      - script: echo "Using agent: $(Agent.Name)"
        displayName: 'Agent Info'
      - task: AzureCLI@2
        inputs:
          azureSubscription: 'HolyCheese-ServiceConnection'
          scriptType: bash
          scriptLocation: inlineScript
          inlineScript: |
            az deployment sub create \
              --location ${{ env.value.location }} \
              --template-file infra/deploy-environment.bicep \
              --parameters \
                appName=AzdoTools \
                environmentName=${{ env.key }} \
                location=${{ env.value.location }} \
                subscriptionId=${{ parameters.subscriptionId }}
      - script: echo "##vso[task.setvariable variable=${{ env.key }}AgentFallback;isOutput=true]true"
        displayName: 'Mark Fallback Active'

  - stage: Deploy_${{ env.key }}
    displayName: 'Direct Deploy to ${{ env.key }} (Local Agent)'
    condition: eq(parameters.useHostedAgent, false)
    jobs:
    - job: DeployDirect_${{ env.key }}
      pool:
        name: ${{ parameters.localAgentName }}
      steps:
      - script: echo "Using agent: $(Agent.Name)"
        displayName: 'Agent Info'
      - task: AzureCLI@2
        inputs:
          azureSubscription: 'HolyCheese-ServiceConnection'
          scriptType: bash
          scriptLocation: inlineScript
          inlineScript: |
            az deployment sub create \
              --location ${{ env.value.location }} \
              --template-file infra/deploy-environment.bicep \
              --parameters \
                appName=AzdoTools \
                environmentName=${{ env.key }} \
                location=${{ env.value.location }} \
                subscriptionId=${{ parameters.subscriptionId }}
