parameters:
  - name: appName
    type: string
  - name: environmentName
    type: string
  - name: resourceGroup
    type: string
  - name: location
    type: string

jobs:
  - job: DeployEnvironment
    displayName: Deploy ${{ parameters.environmentName }} environment
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - checkout: self

      - script: |
          envFile="infra/environments/${{ parameters.appName }}-${{ parameters.environmentName }}.bicep"
          echo "Using file: $envFile"

          az deployment group create \
            --resource-group ${{ parameters.resourceGroup }} \
            --template-file $envFile \
            --parameters appName=${{ parameters.appName }} \
                         environmentName=${{ parameters.environmentName }} \
                         location=${{ parameters.location }}
        displayName: Run AZ Deployment
