parameters:
  solution: 'src/HolyCheeseAzdoTools.sln'
  outputFolder: 'build/functionapp'

steps:
- task: DotNetCoreCLI@2
  displayName: 'Build Solution'
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: ${{ parameters.solution }}
    arguments: '--configuration Release --output ${{ parameters.outputFolder }}'

- publish: ${{ parameters.outputFolder }}
  artifact: 'functionapp'
