parameters:
- name: targetEnvs
  type: object
- name: appName
  type: string
- name: packageVersion
  type: string

stages:
- stage: App
  displayName: App
  jobs:
  - job: Build
    displayName: Build ${{ parameters.appName }}
    pool:
      name: 'Azure Pipelines'
      vmImage: 'windows-latest'
    steps:
    - task: UseDotNet@2
      displayName: Setup .NET SDK
      inputs:
        packageType: 'sdk'
        version: '8.0.x'  # or use a pipeline variable if preferred
    - task: PowerShell@2
      displayName: Build app
      inputs:
        pwsh: true
        filePath: ops/scripts/build-app.ps1
        arguments: -App ${{ parameters.appName }}

  # Publish per environment
  - ${{ each envName in parameters.targetEnvs }}:
    - job: Publish_${{ envName }}
      displayName: Publish package (${{ envName }})
      dependsOn: Build
      pool:
        name: 'Azure Pipelines'
        vmImage: 'windows-latest'
      steps:
      - task: AzureCLI@2
        displayName: Publish to blob (${{ envName }})
        inputs:
          azureSubscription: azureServiceConnection
          scriptType: pscore
          scriptLocation: inlineScript
          inlineScript: |
            pwsh -File ops/scripts/publish-package.ps1 -Envs '${{ envName }}' -App '${{ parameters.appName }}'

  # Deploy per environment
  - ${{ each envName in parameters.targetEnvs }}:
    - job: Deploy_${{ envName }}
      displayName: Deploy ${{ parameters.appName }} (${{ envName }})
      dependsOn: Publish_${{ envName }}
      pool:
        name: 'Azure Pipelines'
        vmImage: 'windows-latest'
        environment: ${{ format('AzdoTools-{0}', envName) }}
      steps:
      - task: AzureCLI@2
        displayName: Infra readiness check (${{ envName }})
        inputs:
          azureSubscription: azureServiceConnection
          scriptType: pscore
          scriptLocation: scriptPath
          scriptPath: ops/scripts/check-infra.ps1
          arguments: -Env ${{ envName }}
      - task: AzureCLI@2
        displayName: Deploy function (${{ envName }})
        inputs:
          azureSubscription: azureServiceConnection
          scriptType: pscore
          scriptLocation: inlineScript
          inlineScript: |
            $version = '${{ parameters.packageVersion }}'
            if ([string]::IsNullOrWhiteSpace($version)) { $version = 'auto' }
            pwsh -File ops/scripts/deploy-app.ps1 -Env '${{ envName }}' -App '${{ parameters.appName }}' -Version $version
