parameters:
  - name: appName
    type: string
  - name: environmentName
    type: string
  - name: location
    type: string
    default: 'centralus'
  - name: resourceGroup
    type: string
  - name: agentPoolName
    type: string
  - name: subscriptionId
    type: string

jobs:
- job: DeployInfra
  displayName: 'Provision Environment'
  pool:
    name: ${{ parameters.agentPoolName }}
    vmImage: 'ubuntu-latest'
  steps:
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'HolyCheese-ServiceConnection'
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          az deployment sub create \
            --location ${{ parameters.location }} \
            --template-file infra/deploy-environment.bicep \
            --parameters \
              appName=${{ parameters.appName }} \
              environmentName=${{ parameters.environmentName }} \
              location=${{ parameters.location }} \
              subscriptionId=${{ parameters.subscriptionId }}

      displayName: 'Deploy Environment Bicep'
