trigger:
  branches:
    include:
      - main

parameters:
  - name: environments
    type: object
    default:
      dev:
        location: 'centralus'
        resourceGroup: 'HolyCheese-RG'

stages:
  # Static infra provision stage
  - stage: InfraProvision
    displayName: 'Infra Loop Delegate'
    jobs:
    - template: ../infra/pipelines/infra-provision-loop.yml
      parameters:
        environmentName: 'dev'
        location: 'centralus'
        resourceGroup: 'HolyCheese-RG'

  # Loop over dynamic environments
  - ${{ each env in parameters.environments }}:
    - stage: Deploy_${{ env.key }}
      displayName: 'Deploy to ${{ env.key }}'
      jobs:
      - template: pipelines/templates/deploy-environment.yml
        parameters:
          environmentName: ${{ env.key }}
          location: ${{ env.value.location }}
          resourceGroup: ${{ env.value.resourceGroup }}
