trigger:
  branches:
    include:
      - dev

pr: none

parameters:
  - name: resourceType
    default: 'Microsoft.Web/sites'

variables:
  functionAppName: 'AzdoTools'
  notes: 'Deploying to dev for internal validation'
  healthCheckUrl: 'https://azdotools-dev.azurewebsites.net/api/health'
  metadataArtifactName: 'Metadata'
  provisionArtifactName: 'ProvisionResult'
  manifestFilePath: '$(Build.SourcesDirectory)/templates/manifest-update.yml'

resources:
  pipelines:
    - pipeline: infraProvision
      source: AzdoTools-Infrastructure
      trigger: none

stages:
- stage: ValidateInfra
  displayName: 'Validate Dev Environment Provisioning'
  jobs:
  - job: ValidateDevInfra
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - download: infraProvision
      artifact: ${{ variables.metadataArtifactName }}

    - task: PowerShell@2
      displayName: 'Read Artifact Metadata'
      inputs:
        targetType: 'filePath'
        filePath: '$(Build.SourcesDirectory)/scripts/Read-ArtifactMetadata.ps1'
        arguments: >
          -MetadataPath "$(Pipeline.Workspace)/${{ variables.metadataArtifactName }}/artifact-metadata.json"

    - download: infraProvision
      artifact: ${{ variables.provisionArtifactName }}

    - task: PowerShell@2
      displayName: 'Validate Provisioning Result'
      inputs:
        targetType: 'filePath'
        filePath: '$(Build.SourcesDirectory)/scripts/Validate-ProvisionResult.ps1'
        arguments: >
          -ResultFilePath "$(Pipeline.Workspace)/${{ variables.provisionArtifactName }}/$(provisionResultPath)"
          -EnvName "dev"

- stage: BuildAndTest
  displayName: 'Build and Run Unit Tests'
  dependsOn: ValidateInfra
  condition: succeeded()
  jobs:
  - job: BuildAndTest
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - checkout: self

    - task: DotNetCoreCLI@2
      displayName: 'Build Solution'
      inputs:
        command: 'build'
        projects: '**/*.csproj'

    - task: DotNetCoreCLI@2
      displayName: 'Run Unit Tests'
      inputs:
        command: 'test'
        projects: '**/*UnitTests.csproj'
        arguments: '--configuration Release --no-build'

- stage: Deploy
  displayName: 'Deploy to Dev Environment'
  dependsOn: BuildAndTest
  condition: succeeded()
  jobs:
  - job: DeployFunctionApp
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - checkout: self

    - template: ${variables.manifestFilePath}
      parameters:
        version: $(Build.BuildNumber)
        branch: $(Build.SourceBranchName)
        commit: $(Build.SourceVersion)
        environment: 'dev'
        notes: $(notes)

  - job: HealthCheck
    dependsOn: DeployFunctionApp
    condition: succeeded()
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: PowerShell@2
      displayName: 'Health Check'
      inputs:
        targetType: 'filePath'
        filePath: '$(Build.SourcesDirectory)/scripts/HealthCheck.ps1'
        arguments: >
          -Url $(healthCheckUrl)
