# Global, centralized configuration for org/app/paths/URIs and pipeline wiring.
globals:
  org: "holycheese"                 # Resource naming org token
  app: "azdotools"                  # Resource naming app token
  owner: "edward"                   # Tag owner value
  subscriptionId: "42a2eb5c-8d13-451c-8b50-069e05cdbf86"

paths:    # All paths are relative to repo root
  config: "ops/config.yml"
  envCatalog: "ops/env-catalog.yml"
  namingModule: "ops/naming.psm1"
  scripts:
    deployInfra: "ops/scripts/deploy-infra.ps1"
    checkInfra: "ops/scripts/check-infra.ps1"
    deployShared: "ops/scripts/deploy-shared.ps1"
    buildApp: "ops/scripts/build-app.ps1"
    publishPackage: "ops/scripts/publish-package.ps1"
    deployApp: "ops/scripts/deploy-app.ps1"
  templates:
    stageInfra: "ops/templates/stage-infra.yml"
    stageApp: "ops/templates/stage-app.yml"
  appBuildSpec: "apps/{0}/app.build.yml"  # {0} will be replaced by the actual app name later
  appDeploySpec: "apps/{0}/app.deploy.yml"
  bicep:
    main: "infra/bicep/main.bicep"
    shared: "infra/bicep/modules/shared-resources.bicep"
  functionProject: "src/TagRouterAzureFunction" 
  publishDir: "publish"
  packagePath: "apps/{0}/dist/{0}.zip"

pipeline:
  azureServiceConnection: "HolyCheese-ServiceConnection"
  # Hosted agent is Azure Pipelines; we still specify vmImage per job.

deployment:
  containerName: "function-packages"  # blob container for function packages
  healthCheckPath: "/api/ping"        # shared health check path for all envs
  defaultDotnetSdk: "8.0.x"           # .NET SDK for build

shared:
  resourceGroup: "AzdoTools-Shared-RG"
  appInsightsName: "AzdoTools-Shared-Insights"
  planName: "AzdoTools-AppServicePlan-Shared"

